import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mehedi Mehad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/soft-skills.png" />
      <body className={inter.className}>
        <Navbar></Navbar>
        {children}
        
        </body>
    </html>
  );
}
